version: "3"
services:
  dev_db:
    image: postgres
    ports:
      - 5432
    environment:
      - PG_PASSWORD=password
  cog:
    container_name: cog
    image: cog:latest
    build:
      context: .
    environment:
      - ENV=development
      - SECRET=not_a_secret
      - LOGIN_URL=https://login.dev.treehacks.com
      - COGNITO_USER_POOL_ID=us-east-1_zraMJaf9F
      - COGNITO_CLIENT_ID=i67d5iv8bqf2f6ele3du1j08l
      - DATABASE_URI=postgres://postgres:password@dev_db/postgres
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - dev_db
    volumes:
      - .:/cog