apiVersion: v1
kind: Service
metadata:
  name: cog-hackthenorth-com
  labels:
    app: cog-hackthenorth-com
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: cog-hackthenorth-com
  selector:
    app: cog-hackthenorth-com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cog-hackthenorth-com
  labels:
    app: cog-hackthenorth-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cog-hackthenorth-com
  template:
    metadata:
      labels:
        app: cog-hackthenorth-com
    spec:
      containers:
      - name: database
        image: postgres:9.6-alpine
        env:
        - name: POSTGRES_PASSWORD
          value: password
        resources:
          requests:
            cpu: 25m
            memory: "0.05G"
      - name: cog-hackthenorth-com
        image: gcr.io/htn-techyon/cog-hackthenorth-com
        ports:
        - containerPort: 80
        env:
        - name: ENV
          value: test
        - name: DATABASE_URI
          value: "$env_db"
        - name: SECRET
          value: "$env_secret"
        resources:
          limits:
            cpu: 25m
            memory: "0.05G"